# Estágio de build
FROM node:14 as build-stage

# Definir o diretório de trabalho
WORKDIR /app

# Copiar o package.json e package-lock.json para o diretório de trabalho
COPY package*.json ./

# Instalar as dependências do projeto
RUN npm install

# Copiar os arquivos do projeto para o diretório de trabalho
COPY . .

# Executar o comando de build da aplicação
RUN npm run build

# Estágio de produção
FROM nginx:alpine as production-stage

# Copiar os arquivos de build do estágio de build para o diretório de publicação do Nginx
COPY --from=build-stage /app/build /usr/share/nginx/html

# Copiar o arquivo de configuração do Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expor a porta 80 para acessar a aplicação
EXPOSE 3000

# Comando para iniciar o Nginx no contêiner
CMD ["nginx", "-g", "daemon off;"]
