

version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=transportadora

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3009:3009
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
  
  frontend:
    build:
      context: ../app  # caminho para a pasta do frontend
      dockerfile: Dockerfile  # caminho para o arquivo Dockerfile do frontend
    ports:
      - 3000:3000  # mapeamento de porta para acessar o frontend
    depends_on:
      - nodejs  # dependência do serviço backend
    environment:
      - REACT_APP_API_URL=http://localhost:3009  # URL da API backend

